{{- $fullName := include "test.fullname" . -}}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "test.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: "Host(`{{ .Values.ingressRoute.route.host }}`)"
      kind: Rule
      services:
        - kind: Service
          name: {{ $fullName }}
          port: 80
